"""Tests for the viva pack builder.

    .venv/bin/python -m pytest demo/test_viva_pack.py -q

The pack is a viewing layer over frozen artefacts, so the tests check
three things: the build's own assertions pass, the generated page carries
the headline numbers exactly as the artefacts state them, and every
artefact the pack reads is committed (mirroring the repository's
artefact-citation guarantee).
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

DEMO = Path(__file__).resolve().parent
REPO = DEMO.parent
sys.path.insert(0, str(DEMO))

import build_viva_pack as bvp  # noqa: E402


@pytest.fixture(scope="module")
def html() -> str:
    return bvp.build()


def test_build_assertions_pass(html):
    assert html.startswith("<!-- generated by demo/build_viva_pack.py")


def test_headline_numbers_present(html):
    # v2 combined 31-90 days: the abstract's numbers, from the frozen CSV.
    for needle in ("4.205", "+0.240", "+0.078", "+0.387",  # combined
                   "4.177", "+0.268", "+0.109", "+0.411",  # national
                   "4.514", "0.7188", "0.8053"):           # baseline refs
        found = needle in html
        assert found, needle


def test_sections_and_interactivity_present(html):
    for anchor in [f'id="s{i}"' for i in range(10)]:
        found = anchor in html
        assert found, anchor
    for token in ("var CONF=", "var SCEN=", "var CODE=", "confUpdate",
                  "scenUpdate", "codeSearch", "openFile",
                  "t18_synthetic_scenarios.csv"):
        found = token in html
        assert found, token


def test_code_provenance_present(html):
    # Every provenance key renders a hidden div, and the excerpts are the
    # real committed functions, extracted (not typed) at build time.
    for key in bvp.PROV:
        found = f"id='prov-{key}'" in html
        assert found, key
    for needle in ("def t05_confirmatory_v2", "def _bootstrap_rows",
                   "def perturb_features", "def run_scenario",
                   "def aggregate_v2_residuals",
                   "id='modal'", "openProv"):
        found = needle in html
        assert found, needle


def test_annotations_present(html):
    # Every annotated function renders its plain-language companion, and
    # the annotation never replaces the verbatim excerpt.
    for needle in ("Problem it solves:", "Numbers it produces:",
                   "ΔMAE = control error − news error",
                   "the contest is the independent unit"):
        found = needle in html
        assert found, needle
    for key in bvp.ANNOTATIONS:
        module, func = key.rsplit(".", 1)
        found = f"{module}.{func}()" in html
        assert found, key


def test_provenance_matches_repo_source(html):
    # A spot check that an embedded excerpt is verbatim repository code.
    src = bvp.extract_function(
        bvp.SRC_NM / "synthetic_news_scenarios.py", "perturb_features")
    found = bvp.esc(src) in html
    assert found


def test_script_block_is_html_safe(html):
    # The HTML tokenizer knows nothing about JSON string boundaries: a
    # raw "</script>", "<script" or "<!--" inside the inline script
    # (embedded sources contain all three) silently derails parsing in
    # browsers even though the JS itself is valid. All "<" inside the
    # embedded JSON must therefore be <-escaped.
    script = html.split("<script>var CONF=", 1)[1].rsplit("</script>", 1)[0]
    for token in ("</script", "<script", "<!--"):
        found = token in script
        assert not found, token


def test_no_network_dependencies(html):
    # The pack must work fully offline: no external URLs are loaded from
    # the page markup. The embedded code navigator sources (inside the
    # trailing <script> block) legitimately mention URLs as data, so only
    # the markup before the scripts is scanned.
    markup = html.split("<script>", 1)[0]
    for token in ("src='http", 'src="http', "href='http", 'href="http',
                  "@import", "fetch("):
        found = token in markup
        assert not found, token


def test_inputs_are_committed():
    tracked = set(bvp.tracked_files())
    needed = [f"outputs/report_tables_v1/{p.name}"
              for p in bvp.TABLES.glob("t*.csv")]
    needed += ["outputs/report_tables_v1/manifest.json",
               "outputs/report_tables_v1/latex/a1_stage1_predictors.tex",
               "outputs/report_tables_v1/latex/a5_llm_validation.tex"]
    needed += [f"outputs/report_figures_v1/{n}" for n in
               ("fig0_study_design.png", "fig0b_corpus_funnel.png",
                "fig0c_framework.png", "fig1_confirmatory_deltas.png",
                "fig2_seat_totals.png", "fig5_party_resolution.png",
                "fig4_island_contrast.png", "fig6_mechanism_vs_outcome.png")]
    missing = [n for n in needed if n not in tracked]
    assert not missing, missing


def test_output_is_gitignored():
    out = subprocess.run(
        ["git", "check-ignore", "demo/viva_pack.html"],
        cwd=REPO, capture_output=True, text=True)
    assert out.returncode == 0, "demo/viva_pack.html must stay untracked"
